esphome:
  name: plmcovercontrol
  includes:
    - plm_cover.h
  libraries:
    - EspSoftwareSerial
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi: !include "wifi.private.yaml"

captive_portal:
  

cover:
- platform: custom
  lambda: |-
    auto c0 = new PLMCover();
    c0->setID(1);
    App.register_component(c0);
    auto c1 = new PLMCover();
    c1->setID(2);
    App.register_component(c1);
    auto c2 = new PLMCover();
    c2->setID(3);
    App.register_component(c2);
    auto c3 = new PLMCover();
    c3->setID(4);
    App.register_component(c3);
    return {c0,c1,c2,c3};

  covers:
    - name: "PLMCover0"
    - name: "PLMCover1"
    - name: "PLMCover2"
    - name: "PLMCover3"