esphome:
  name: plmcovercontrol
  includes:
    - plmcover.h
  libraries:
    - EspSoftwareSerial
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi: !include "wifi.private.yaml"

captive_portal:
  

cover:
- platform: custom
  lambda: |-
    auto rs485cover = new RS485Cover();
    App.register_component(rs485cover);
    auto c0 = new PLMCover(1, rs485cover);
    App.register_component(c0);
    auto c1 = new PLMCover(2, rs485cover);
    App.register_component(c1);
    auto c2 = new PLMCover(3, rs485cover);
    App.register_component(c2);
    auto c3 = new PLMCover(4, rs485cover);
    App.register_component(c3);
    return {c0,c1,c2,c3};

  covers:
    - name: "PLMCover0"
    - name: "PLMCover1"
    - name: "PLMCover2"
    - name: "PLMCover3"